{"uuid": "3917d901-18ce-4cbd-98ee-1fbb3bfa7a33", "children": ["a836eca8-df02-4d42-ae30-953a4c1cf924"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x56374bb60133 <unknown>\n#1 0x56374b894966 <unknown>\n#2 0x56374b8b1a51 <unknown>\n#3 0x56374b8b8551 <unknown>\n#4 0x56374b8b11b3 <unknown>\n#5 0x56374b8f8025 <unknown>\n#6 0x56374b8f7a11 <unknown>\n#7 0x56374b8f9386 <unknown>\n#8 0x56374b8f918f <unknown>\n#9 0x56374b8f09a3 <unknown>\n#10 0x56374b8c546a <unknown>\n#11 0x56374b8c655e <unknown>\n#12 0x56374bb1fcae <unknown>\n#13 0x56374bb238fe <unknown>\n#14 0x56374bb2cf20 <unknown>\n#15 0x56374bb24923 <unknown>\n#16 0x56374baf7c0e <unknown>\n#17 0x56374bb47b08 <unknown>\n#18 0x56374bb47c97 <unknown>\n#19 0x56374bb58113 <unknown>\n#20 0x7fd547894b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920097335, "stop": 1684920099146}], "start": 1684920097335, "stop": 1684920099171}