{"uuid": "170e605c-d2b5-43b4-911a-dfd3d5880407", "children": ["bf477aa3-4b7a-40aa-a260-ccf5b7ba5007"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55892e86d133 <unknown>\n#1 0x55892e5a1966 <unknown>\n#2 0x55892e5bea51 <unknown>\n#3 0x55892e5c5551 <unknown>\n#4 0x55892e5be1b3 <unknown>\n#5 0x55892e605025 <unknown>\n#6 0x55892e604a11 <unknown>\n#7 0x55892e606386 <unknown>\n#8 0x55892e60618f <unknown>\n#9 0x55892e5fd9a3 <unknown>\n#10 0x55892e5d246a <unknown>\n#11 0x55892e5d355e <unknown>\n#12 0x55892e82ccae <unknown>\n#13 0x55892e8308fe <unknown>\n#14 0x55892e839f20 <unknown>\n#15 0x55892e831923 <unknown>\n#16 0x55892e804c0e <unknown>\n#17 0x55892e854b08 <unknown>\n#18 0x55892e854c97 <unknown>\n#19 0x55892e865113 <unknown>\n#20 0x7f8a25094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920158666, "stop": 1684920160759}], "start": 1684920158666, "stop": 1684920160797}