{"uuid": "15627aed-f259-4600-b7c4-2d1c6efcb463", "children": ["0f997261-5049-4d9d-bcf5-a8cdef9ea0d8"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x555cfa9f3133 <unknown>\n#1 0x555cfa727966 <unknown>\n#2 0x555cfa744a51 <unknown>\n#3 0x555cfa74b551 <unknown>\n#4 0x555cfa7441b3 <unknown>\n#5 0x555cfa78b025 <unknown>\n#6 0x555cfa78aa11 <unknown>\n#7 0x555cfa78c386 <unknown>\n#8 0x555cfa78c18f <unknown>\n#9 0x555cfa7839a3 <unknown>\n#10 0x555cfa75846a <unknown>\n#11 0x555cfa75955e <unknown>\n#12 0x555cfa9b2cae <unknown>\n#13 0x555cfa9b68fe <unknown>\n#14 0x555cfa9bff20 <unknown>\n#15 0x555cfa9b7923 <unknown>\n#16 0x555cfa98ac0e <unknown>\n#17 0x555cfa9dab08 <unknown>\n#18 0x555cfa9dac97 <unknown>\n#19 0x555cfa9eb113 <unknown>\n#20 0x7f689b494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 28, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684919920332, "stop": 1684919922521}], "start": 1684919920332, "stop": 1684919922548}