{"uuid": "e0f4bb45-4bc3-4898-824f-368ae687c881", "children": ["d25908fa-62fe-4d38-bf13-a9c18c935e6a"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55fc6cd1e133 <unknown>\n#1 0x55fc6ca52966 <unknown>\n#2 0x55fc6ca6fa51 <unknown>\n#3 0x55fc6ca76551 <unknown>\n#4 0x55fc6ca6f1b3 <unknown>\n#5 0x55fc6cab6025 <unknown>\n#6 0x55fc6cab5a11 <unknown>\n#7 0x55fc6cab7386 <unknown>\n#8 0x55fc6cab718f <unknown>\n#9 0x55fc6caae9a3 <unknown>\n#10 0x55fc6ca8346a <unknown>\n#11 0x55fc6ca8455e <unknown>\n#12 0x55fc6ccddcae <unknown>\n#13 0x55fc6cce18fe <unknown>\n#14 0x55fc6cceaf20 <unknown>\n#15 0x55fc6cce2923 <unknown>\n#16 0x55fc6ccb5c0e <unknown>\n#17 0x55fc6cd05b08 <unknown>\n#18 0x55fc6cd05c97 <unknown>\n#19 0x55fc6cd16113 <unknown>\n#20 0x7fc1db094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920100509, "stop": 1684920102955}], "start": 1684920100509, "stop": 1684920102980}