{"uuid": "5380ce88-4925-4289-90ce-a0d7ad8d7afc", "children": ["d465ba11-4cee-4ac5-9ffa-b6ef696f72d5"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55efad907133 <unknown>\n#1 0x55efad63b966 <unknown>\n#2 0x55efad658a51 <unknown>\n#3 0x55efad65f551 <unknown>\n#4 0x55efad6581b3 <unknown>\n#5 0x55efad69f025 <unknown>\n#6 0x55efad69ea11 <unknown>\n#7 0x55efad6a0386 <unknown>\n#8 0x55efad6a018f <unknown>\n#9 0x55efad6979a3 <unknown>\n#10 0x55efad66c46a <unknown>\n#11 0x55efad66d55e <unknown>\n#12 0x55efad8c6cae <unknown>\n#13 0x55efad8ca8fe <unknown>\n#14 0x55efad8d3f20 <unknown>\n#15 0x55efad8cb923 <unknown>\n#16 0x55efad89ec0e <unknown>\n#17 0x55efad8eeb08 <unknown>\n#18 0x55efad8eec97 <unknown>\n#19 0x55efad8ff113 <unknown>\n#20 0x7fd45a294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 28, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684919917516, "stop": 1684919919337}], "start": 1684919917516, "stop": 1684919919389}