{"uuid": "bf89957b-4c5b-4df2-b39e-d40d1800f964", "children": ["4717d2dd-b9b4-43a2-a4ac-c1b9ee1eb52b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5577b566d133 <unknown>\n#1 0x5577b53a1966 <unknown>\n#2 0x5577b53bea51 <unknown>\n#3 0x5577b53c5551 <unknown>\n#4 0x5577b53be1b3 <unknown>\n#5 0x5577b5405025 <unknown>\n#6 0x5577b5404a11 <unknown>\n#7 0x5577b5406386 <unknown>\n#8 0x5577b540618f <unknown>\n#9 0x5577b53fd9a3 <unknown>\n#10 0x5577b53d246a <unknown>\n#11 0x5577b53d355e <unknown>\n#12 0x5577b562ccae <unknown>\n#13 0x5577b56308fe <unknown>\n#14 0x5577b5639f20 <unknown>\n#15 0x5577b5631923 <unknown>\n#16 0x5577b5604c0e <unknown>\n#17 0x5577b5654b08 <unknown>\n#18 0x5577b5654c97 <unknown>\n#19 0x5577b5665113 <unknown>\n#20 0x7f0b98c94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920153843, "stop": 1684920156400}], "start": 1684920153843, "stop": 1684920156462}