{"uuid": "6f415f2f-e211-407d-b39d-f48220ec89c5", "children": ["46c457d3-9f20-441c-809d-a832006af5ee"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55c92a6cf133 <unknown>\n#1 0x55c92a403966 <unknown>\n#2 0x55c92a420a51 <unknown>\n#3 0x55c92a427551 <unknown>\n#4 0x55c92a4201b3 <unknown>\n#5 0x55c92a467025 <unknown>\n#6 0x55c92a466a11 <unknown>\n#7 0x55c92a468386 <unknown>\n#8 0x55c92a46818f <unknown>\n#9 0x55c92a45f9a3 <unknown>\n#10 0x55c92a43446a <unknown>\n#11 0x55c92a43555e <unknown>\n#12 0x55c92a68ecae <unknown>\n#13 0x55c92a6928fe <unknown>\n#14 0x55c92a69bf20 <unknown>\n#15 0x55c92a693923 <unknown>\n#16 0x55c92a666c0e <unknown>\n#17 0x55c92a6b6b08 <unknown>\n#18 0x55c92a6b6c97 <unknown>\n#19 0x55c92a6c7113 <unknown>\n#20 0x7fefc3c94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920158361, "stop": 1684920160683}], "start": 1684920158361, "stop": 1684920160713}