{"uuid": "eb77f0ad-9b98-4646-9267-ef4c224c0bb5", "children": ["d28bea4e-ceb9-49f9-8efc-ab982e113f1f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x556dea55c133 <unknown>\n#1 0x556dea290966 <unknown>\n#2 0x556dea2ada51 <unknown>\n#3 0x556dea2b4551 <unknown>\n#4 0x556dea2ad1b3 <unknown>\n#5 0x556dea2f4025 <unknown>\n#6 0x556dea2f3a11 <unknown>\n#7 0x556dea2f5386 <unknown>\n#8 0x556dea2f518f <unknown>\n#9 0x556dea2ec9a3 <unknown>\n#10 0x556dea2c146a <unknown>\n#11 0x556dea2c255e <unknown>\n#12 0x556dea51bcae <unknown>\n#13 0x556dea51f8fe <unknown>\n#14 0x556dea528f20 <unknown>\n#15 0x556dea520923 <unknown>\n#16 0x556dea4f3c0e <unknown>\n#17 0x556dea543b08 <unknown>\n#18 0x556dea543c97 <unknown>\n#19 0x556dea554113 <unknown>\n#20 0x7f836d294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920156060, "stop": 1684920158330}], "start": 1684920156060, "stop": 1684920158359}