{"uuid": "66b7b565-f804-45c3-9939-44555d438606", "children": ["d20d526c-3057-44f3-9947-4678dd94821a"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5649a8080133 <unknown>\n#1 0x5649a7db4966 <unknown>\n#2 0x5649a7dd1a51 <unknown>\n#3 0x5649a7dd8551 <unknown>\n#4 0x5649a7dd11b3 <unknown>\n#5 0x5649a7e18025 <unknown>\n#6 0x5649a7e17a11 <unknown>\n#7 0x5649a7e19386 <unknown>\n#8 0x5649a7e1918f <unknown>\n#9 0x5649a7e109a3 <unknown>\n#10 0x5649a7de546a <unknown>\n#11 0x5649a7de655e <unknown>\n#12 0x5649a803fcae <unknown>\n#13 0x5649a80438fe <unknown>\n#14 0x5649a804cf20 <unknown>\n#15 0x5649a8044923 <unknown>\n#16 0x5649a8017c0e <unknown>\n#17 0x5649a8067b08 <unknown>\n#18 0x5649a8067c97 <unknown>\n#19 0x5649a8078113 <unknown>\n#20 0x7f075cc94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 26, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/.cache/pypoetry/virtualenvs/devops-sandbox-XsxpJM04-py3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684920101105, "stop": 1684920103017}], "start": 1684920101105, "stop": 1684920103039}